export enum LanguageKey {
  C = 'C',
  CSharp = 'C#',
  Clojure = 'Clojure',
  CoffeeScript = 'CoffeeScript',
  CSS = 'CSS',
  Go = 'Go',
  HTML = 'HTML',
  Java = 'Java',
  JavaScript = 'JavaScript',
  Kotlin = 'Kotlin',
  ObjectiveC = 'Objective-C',
  PHP = 'PHP',
  Python = 'Python',
  Ruby = 'Ruby',
  Rust = 'Rust',
  Scala = 'Scala',
  Swift = 'Swift',
  TypeScript = 'TypeScript',
}
